name: Envío de Email Programado

on:
  schedule:
    - cron: "*/5 * * * *"  # Se ejecuta cada 5 minutos
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # python-dotenv
      
      - name: Mostrar hora de ejecucion
        run: date

      - name: Ejecutar script de envío de email
        env:
          EMAIL_USER_1: ${{ secrets.EMAIL_USER_1 }}
          EMAIL_PASSWORD_1: ${{ secrets.EMAIL_PASSWORD_1 }}
          EMAIL_USER_2: ${{ secrets.EMAIL_USER_2 }}
          EMAIL_PASSWORD_2: ${{ secrets.EMAIL_PASSWORD_2 }}
          EMAIL_USER_3: ${{ secrets.EMAIL_USER_3 }}
          EMAIL_PASSWORD_3: ${{ secrets.EMAIL_PASSWORD_3 }}
          EMAIL_USER_4: ${{ secrets.EMAIL_USER_4 }}
          EMAIL_PASSWORD_4: ${{ secrets.EMAIL_PASSWORD_4 }}
          EMAIL_USER_5: ${{ secrets.EMAIL_USER_5 }}
          EMAIL_PASSWORD_5: ${{ secrets.EMAIL_PASSWORD_5 }}
        run: python3 cjemail.py
